
-- Inserts para a tabela ALUNO
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Rogério', TO_DATE('1974-07-31', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Giovane', TO_DATE('1975-03-26', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('João ', TO_DATE('1988-11-20', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Maria', TO_DATE('1988-10-20', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Tereza', TO_DATE('1982-10-07', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Alexandre', TO_DATE('1988-05-30', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Arthur', TO_DATE('1989-05-28', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Angela', TO_DATE('1972-03-02', 'YYYY-MM-DD'));
INSERT INTO ALUNO (NOME, DATA_NASC) VALUES ('Vinicius', TO_DATE('1994-02-01', 'YYYY-MM-DD'));

-- Inserts para a tabela PROFESSOR
INSERT INTO PROFESSOR (NOME) VALUES ('Maíra');
INSERT INTO PROFESSOR (NOME) VALUES ('Zezé');
INSERT INTO PROFESSOR (NOME) VALUES ('Alexandre');
INSERT INTO PROFESSOR (NOME) VALUES ('Arthur');

-- Inserts para a tabela DISCIPLINA
INSERT INTO DISCIPLINA (NOME, PRE_REQUISITO_ID, CREDITO, PROFESSOR_ID) VALUES ('Sistema de Informação', NULL, 2, 2);
INSERT INTO DISCIPLINA (NOME, PRE_REQUISITO_ID, CREDITO, PROFESSOR_ID) VALUES ('Sistema de Informação II', 1, 2, 4);
INSERT INTO DISCIPLINA (NOME, PRE_REQUISITO_ID, CREDITO, PROFESSOR_ID) VALUES ('Banco de Dados', NULL, 2, 1);
INSERT INTO DISCIPLINA (NOME, PRE_REQUISITO_ID, CREDITO, PROFESSOR_ID) VALUES ('Português', NULL, 4, 2);
INSERT INTO DISCIPLINA (NOME, PRE_REQUISITO_ID, CREDITO, PROFESSOR_ID) VALUES ('Banco de Dados II', 3, 4, 4);

-- Inserts para a tabela MATRICULA
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (1, 5, 2, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (1, 1, 9, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (1, 2, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (1, 3, 6, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (1, 4, 4, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (4, 1, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (4, 2, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (4, 3, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (4, 4, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (4, 5, 6, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (2, 1, 5, 'Aprovador');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (2, 2, 4, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (2, 3, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (2, 4, 2, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (2, 5, 6, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (3, 4, 3, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (3, 1, 6, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (3, 2, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (3, 3, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (3, 5, 9, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (5, 1, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (5, 2, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (5, 3, 5, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (5, 4, 5, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (5, 5, 6, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (6, 1, 5, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (6, 2, 4, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (6, 3, 3, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (6, 4, 4, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (6, 5, 2, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (7, 1, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (7, 2, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (7, 3, 9, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (7, 4, 5, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (7, 5, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (8, 1, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (8, 2, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (8, 3, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (8, 4, 10, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (8, 5, 9, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (9, 1, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (9, 2, 8, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (9, 3, 7, 'Aprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (9, 4, 3, 'Reprovado');
INSERT INTO MATRICULA (ALUNO_ID, DISCIPLINA_ID, NOTA, SITUACAO) VALUES (9, 5, 6, 'Aprovado');
